f=open("abcd.txt", "w")
print("Name", f.name)
print("Mode", f.mode)
print("Is Closed", f.closed)
print("Is Readable", f.readable())
print("Is Writable", f.writable())
f.write("Write data in the file \n")
list=['lalit\n','sagar\n','abcd\n','wxyz\n']
f.writelines(list)
print("All lines from the list written to the file")
f.close()
print("Is Closed", f.closed)
f=open("abcd.txt")
line1=f.readline()
print(line1,end='')
line2=f.readline()
print(line2,end='')
line3=f.readline()
print(line3)
f.close()
f=open("abcd.txt")
lines=f.readlines()
for line in lines:
    print(line, end="")
f.close()